// i2s_output.cpp — PIO + DMA I2S audio driver implementation
//
// SPDX-License-Identifier: BSD-3-Clause

#include "i2s_output.h"
#include "i2s_output.pio.h"   // generated by pico_generate_pio_header()

#include "hardware/clocks.h"
#include "hardware/dma.h"
#include "hardware/irq.h"
#include "hardware/pio.h"

#include <cstring>

// ─── Singleton ───────────────────────────────────────────────────────────────

I2SOutput* I2SOutput::instance_ = nullptr;

// ─── Destructor ──────────────────────────────────────────────────────────────

I2SOutput::~I2SOutput() {
    if (initialized_) {
        stop();
        irq_set_enabled(DMA_IRQ_0, false);
        dma_channel_unclaim(dma_chan_[0]);
        dma_channel_unclaim(dma_chan_[1]);
        pio_sm_unclaim(pio_, sm_);
        pio_remove_program(pio_, &i2s_output_program, pio_offset_);
        instance_ = nullptr;
    }
}

// ─── init ────────────────────────────────────────────────────────────────────

bool I2SOutput::init(uint data_pin,
                     uint clock_pin_base,
                     uint32_t sample_rate,
                     AudioFillCallback callback) {
    callback_  = callback;
    instance_  = this;

    // ── PIO state machine ────────────────────────────────────────────────────
    pio_       = pio0;
    if (!pio_can_add_program(pio_, &i2s_output_program)) return false;

    sm_         = (uint)pio_claim_unused_sm(pio_, true);
    pio_offset_ = pio_add_program(pio_, &i2s_output_program);

    pio_sm_config c = i2s_output_program_get_default_config(pio_offset_);

    // OUT pin → DIN
    sm_config_set_out_pins(&c, data_pin, 1);
    pio_gpio_init(pio_, data_pin);
    pio_sm_set_consecutive_pindirs(pio_, sm_, data_pin, 1, true);

    // SIDE-SET pins → BCLK (base), LRCLK (base+1)
    sm_config_set_sideset_pins(&c, clock_pin_base);
    pio_gpio_init(pio_, clock_pin_base);
    pio_gpio_init(pio_, clock_pin_base + 1);
    pio_sm_set_consecutive_pindirs(pio_, sm_, clock_pin_base, 2, true);

    // OSR: shift LEFT (MSB first), autopull at 32 bits
    sm_config_set_out_shift(&c, false, true, 32);

    // Join both FIFOs into TX for deeper buffering
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);

    // Clock divider: PIO runs at sample_rate × 64 cycles/frame
    //   (32 bits × 2 half-cycles per bit)
    float clkdiv = (float)clock_get_hz(clk_sys) / ((float)sample_rate * 64.0f);
    sm_config_set_clkdiv(&c, clkdiv);

    // Initialise SM at the entry_point label (sets x=14 and idles the clocks)
    pio_sm_init(pio_, sm_, pio_offset_ + i2s_output_offset_entry_point, &c);

    // ── DMA channels (ping-pong) ─────────────────────────────────────────────
    dma_chan_[0] = (uint)dma_claim_unused_channel(true);
    dma_chan_[1] = (uint)dma_claim_unused_channel(true);

    for (uint i = 0; i < 2; i++) {
        dma_channel_config dc = dma_channel_get_default_config(dma_chan_[i]);
        channel_config_set_transfer_data_size(&dc, DMA_SIZE_32);
        channel_config_set_read_increment(&dc, true);
        channel_config_set_write_increment(&dc, false);
        channel_config_set_dreq(&dc, pio_get_dreq(pio_, sm_, true));
        // Chain: channel 0 → 1 → 0 → …
        channel_config_set_chain_to(&dc, dma_chan_[1 - i]);

        dma_channel_configure(
            dma_chan_[i], &dc,
            &pio_->txf[sm_],   // write address: PIO TX FIFO (fixed)
            buffers_[i],        // read address: audio buffer i
            BUF_WORDS,          // transfer count
            false               // don't start yet
        );
    }

    // ── DMA IRQ ──────────────────────────────────────────────────────────────
    dma_channel_set_irq0_enabled(dma_chan_[0], true);
    dma_channel_set_irq0_enabled(dma_chan_[1], true);
    irq_set_exclusive_handler(DMA_IRQ_0, static_dma_irq_handler);
    irq_set_enabled(DMA_IRQ_0, true);

    initialized_ = true;
    return true;
}

// ─── start / stop ────────────────────────────────────────────────────────────

void I2SOutput::start() {
    if (!initialized_ || running_) return;
    running_ = true;

    // Pre-fill both buffers before handing them to DMA
    fill_buffer(0);
    fill_buffer(1);

    // Enable state machine, then kick off channel 0
    pio_sm_set_enabled(pio_, sm_, true);
    dma_channel_start(dma_chan_[0]);
}

void I2SOutput::stop() {
    if (!running_) return;
    running_ = false;
    pio_sm_set_enabled(pio_, sm_, false);
    dma_channel_abort(dma_chan_[0]);
    dma_channel_abort(dma_chan_[1]);
    // Clear any pending IRQ flags
    dma_channel_acknowledge_irq0(dma_chan_[0]);
    dma_channel_acknowledge_irq0(dma_chan_[1]);
}

// ─── fill_buffer ─────────────────────────────────────────────────────────────
//
// Fills buffers_[buf_idx] from the audio callback then packs the interleaved
// int16_t pairs into uint32_t words: left in [31:16], right in [15:0].
//
// The packing is done in-place using a reverse traversal so we never read a
// sample after its destination word has been written.

void I2SOutput::fill_buffer(uint buf_idx) {
    // Treat the uint32_t buffer as int16_t pairs for the callback
    auto* stereo = reinterpret_cast<int16_t*>(buffers_[buf_idx]);

    uint32_t filled = 0;
    if (callback_) {
        filled = callback_(stereo, BUF_WORDS);
    }

    // Zero-pad any frames the callback did not supply
    if (filled < BUF_WORDS) {
        std::memset(stereo + filled * 2, 0,
                    (BUF_WORDS - filled) * 2 * sizeof(int16_t));
    }

    // In-place pack: iterate backwards so each source pair is read before its
    // overlapping destination word is written.
    for (uint32_t f = BUF_WORDS; f-- > 0;) {
        const int16_t l = stereo[f * 2];
        const int16_t r = stereo[f * 2 + 1];
        buffers_[buf_idx][f] =
            (static_cast<uint32_t>(static_cast<uint16_t>(l)) << 16u) |
             static_cast<uint16_t>(r);
    }
}

// ─── restart_dma_channel ─────────────────────────────────────────────────────

void I2SOutput::restart_dma_channel(uint buf_idx) {
    // Reload the read address so the chained transfer uses the freshly filled
    // buffer (chain_to fires automatically when the *other* channel finishes).
    dma_channel_set_read_addr(dma_chan_[buf_idx], buffers_[buf_idx], false);
}

// ─── IRQ handler ─────────────────────────────────────────────────────────────

void I2SOutput::handle_dma_irq() {
    for (uint i = 0; i < 2; i++) {
        if (dma_channel_get_irq0_status(dma_chan_[i])) {
            dma_channel_acknowledge_irq0(dma_chan_[i]);
            if (running_) {
                // Channel i has just finished playing buffers_[i].
                // Refill it and reset its read pointer so the chain re-uses it.
                fill_buffer(i);
                restart_dma_channel(i);
            }
        }
    }
}

void I2SOutput::static_dma_irq_handler() {
    if (instance_) {
        instance_->handle_dma_irq();
    }
}
