// wav_player.cpp — WavPlayer implementation
//
// SPDX-License-Identifier: BSD-3-Clause

#include "wav_player.h"

#include <algorithm>
#include <cstring>

// ─── load ────────────────────────────────────────────────────────────────────

bool WavPlayer::load(const uint8_t* data, uint32_t size) {
    loaded_     = false;
    done_       = false;
    wav_data_   = nullptr;
    pcm_offset_ = 0u;
    pcm_size_   = 0u;
    read_pos_   = 0u;

    if (!data || size < sizeof(WavHeader)) return false;

    // Copy fixed header fields for easy access.
    std::memcpy(&header_, data, sizeof(WavHeader));

    // Validate mandatory identifiers.
    if (std::memcmp(header_.riff_id,  "RIFF", 4) != 0) return false;
    if (std::memcmp(header_.wave_id,  "WAVE", 4) != 0) return false;

    // Only uncompressed PCM is supported.
    if (header_.audio_format != 1u) return false;

    // Only 16-bit samples.
    if (header_.bits_per_sample != 16u) return false;

    // Mono or stereo only.
    if (header_.num_channels < 1u || header_.num_channels > 2u) return false;

    // ── Locate the "data" sub-chunk ─────────────────────────────────────────
    // Walk past the RIFF/WAVE tag and all sub-chunks until we find "data".
    // The standard 44-byte header puts "data" immediately after "fmt ", but
    // files generated by some tools include extra chunks (e.g. "LIST", "ID3").
    uint32_t offset = 12u;  // Skip "RIFF" + riff_size + "WAVE"
    pcm_offset_ = 0u;
    pcm_size_   = 0u;

    while (offset + 8u <= size) {
        char     chunk_id[4];
        uint32_t chunk_size;
        std::memcpy(chunk_id,    data + offset,      4u);
        std::memcpy(&chunk_size, data + offset + 4u, sizeof(uint32_t));

        if (std::memcmp(chunk_id, "data", 4u) == 0) {
            pcm_offset_ = offset + 8u;
            // Clamp to available bytes in case the declared size is wrong.
            pcm_size_   = std::min(chunk_size, size - pcm_offset_);
            break;
        }

        // Advance past this chunk; RIFF chunks are word-aligned.
        offset += 8u + chunk_size;
        if (chunk_size & 1u) ++offset;  // padding byte for odd-length chunks
    }

    if (pcm_size_ == 0u) return false;  // No "data" chunk found.

    wav_data_ = data;
    wav_size_ = size;
    loaded_   = true;
    return true;
}

// ─── reset ───────────────────────────────────────────────────────────────────

void WavPlayer::reset() {
    read_pos_ = 0u;
    done_     = false;
}

// ─── duration_ms ─────────────────────────────────────────────────────────────

uint32_t WavPlayer::duration_ms() const {
    if (!loaded_ || header_.sample_rate == 0u || header_.block_align == 0u) {
        return 0u;
    }
    // bytes / (bytes per frame) / frames_per_second * 1000
    return static_cast<uint32_t>(
        static_cast<uint64_t>(pcm_size_) * 1000u /
        (static_cast<uint32_t>(header_.sample_rate) * header_.block_align));
}

// ─── fill ────────────────────────────────────────────────────────────────────

uint32_t WavPlayer::fill(int16_t* buffer, uint32_t frames) {
    if (!loaded_ || done_) return 0u;

    const auto*    pcm         = reinterpret_cast<const int16_t*>(wav_data_ + pcm_offset_);
    const uint32_t pcm_samples = pcm_size_ / 2u;   // total 16-bit samples
    const uint32_t ch          = header_.num_channels;
    uint32_t       written     = 0u;

    while (written < frames) {
        // read_pos_ tracks bytes consumed from the PCM payload.
        const uint32_t sample_idx = read_pos_ / 2u;  // byte offset → sample index

        if (sample_idx + ch > pcm_samples) {
            done_ = true;
            break;
        }

        if (ch == 2u) {
            // Stereo: left and right are consecutive.
            buffer[written * 2u]      = pcm[sample_idx];
            buffer[written * 2u + 1u] = pcm[sample_idx + 1u];
        } else {
            // Mono: duplicate to both output channels.
            buffer[written * 2u]      = pcm[sample_idx];
            buffer[written * 2u + 1u] = pcm[sample_idx];
        }

        read_pos_ += ch * 2u;  // advance by (ch) samples × 2 bytes each
        ++written;
    }

    return written;
}
